### ISSUE TITLE
having an issue

### ISSUE THREAD

**Issue by RealPolarbrr** [GardeningTool/HostsMod#11]
When I run the exe it says "unable to access hosts file" and I have firewall and everything off, I also run it as administrator.

**Comment by GardeningTool** [comment]
Your hosts file doesn't exist. Google "how to create a hosts file"

**Comment by RealPolarbrr** [comment]
> Your hosts file doesn't exist. Google "how to create a hosts file"

No I have a host file
![hrhresyc](https://user-images.githubusercontent.com/84231914/118371715-bef3c000-b562-11eb-8ba6-e5f90d7dda69.png)

**Comment by GardeningTool** [comment]
I'm not sure then

**Comment by RealPolarbrr** [comment]
Do I maybe make a new hosts file?

**Comment by GardeningTool** [comment]
You could try that.

**Comment by RealPolarbrr** [comment]
Welp I tried, you cant delete it since its getting used.

**Comment by RealPolarbrr** [comment]
Yo garden is there a way to do it manually?

**Comment by GardeningTool** [comment]
> Welp I tried, you cant delete it since its getting used. Unless you disable it but I don't know how to disable it and don't know if its safe to do so.

Close whatever process is accessing your hosts file, then run HostsMod.



> Yo garden is there a way to do it manually?

Yes, this is possible.

1) Open your hosts file in a text editor such as Notepad with administrator
2) Manually append each entry like this:

127.0.0.1 (domain)
