### ISSUE TITLE
Removal of etc.catering

### ISSUE THREAD

**Issue by 0xa00** [GardeningTool/HostsMod#113]
Hello. I am the mother of Aidan W. Dorfler, Katie, and owner of ETC Catering.

This software has seriously damaged my business by blocking our website `etc.catering`

We have not sold any more Curried Lentil Salads in over 2 weeks.
Our overall sales have gone down by 98%, and we suspect this software to be the culprit.

Remove this or expect a lawsuit.

Katie Dorfler

**Comment by WinterTempIQ** [comment]
LMFAO

**Comment by jinja365** [comment]
@0xa00 for real my guy?
lmfaooooooooooooooooooooooooo WTF CURRIED LENTIL SALAD XD

**Comment by LucaForever** [comment]
I can approve, this software made my life **worse** by not being able to buy ETC Caterings' Curried Lentil Salad.
I will file a DMCA lawsuit against this unorthodox practice.

Expect the FBI at your door.

**Comment by apple171017** [comment]
I just wanna fuck a dude 
His cum is so sticky like glue
I make his dick hard and it grew
His dick is so cool
Sucking on it right after school
His dick is all covered in my drool (2x)

**Comment by ignSKRRRTT** [comment]
LMFAO

**Comment by CallumUncensored** [comment]
ples remov els lawyar invoelvment fank u veery muche

**Comment by WinterTempIQ** [comment]
they put the يفدجك in the soder
