### ISSUE TITLE
Helpfull domains to blacklist.

### ISSUE THREAD

**Issue by Enderqq955** [GardeningTool/HostsMod#20]
Hey, I recently watched some videos about using custom DNS to block adware and phishing scams take a look at this blacklisted addresses and I would appreciate if u add it to host-mode as it can improve by a tone. Sorry for writing this as an issue but I don't know if there is any contact with developers other then github if there is discord server or something make sure to drop me a reply.

Blacklisted domains : https://obutterbach.medium.com/unlock-the-full-potential-of-pihole-e795342e0e36 (scroll down)

**Comment by GardeningTool** [comment]
I could add these in the future. The goal of HostsMod was to block malicious domains that may be present in the Minecraft community (such as rats, grabify links, and token logger sites). I'm not sure about adding this yet.

**Comment by Enderqq955** [comment]
Okay :D
