### ISSUE TITLE
guys

### ISSUE THREAD

**Issue by Memexurer** [GardeningTool/HostsMod#3]
why gaymers.ax domain isnt blocked here

**Comment by KtntKot** [comment]
yes

**Comment by Memexurer** [comment]
no

**Comment by Memexurer** [comment]
@GardeningTool fix or gay

**Comment by GardeningTool** [comment]
To the best of my knowledge, that site is not malicious or an IP logger.

**Comment by Memexurer** [comment]
HOW iT'S NOT MALICIOUS

**Comment by Memexurer** [comment]
![image](https://user-images.githubusercontent.com/34003944/116201105-6edec600-a739-11eb-8296-e90701fbe3ef.png)
iT'S LITERALLY HERE

**Comment by KtntKot** [comment]
^^

**Comment by DortDev** [comment]
It's malicious @GardeningTool

**Comment by GardeningTool** [comment]
I wasn't aware of this, I'll add it in immediately.
