### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by gabrielvicenteYT** [GardeningTool/HostsMod#34]
Is it safe to  use autumn crack by kant now? (I have downloaded and ran HostsMod with admin)

**Comment by GardeningTool** [comment]
The malware won't be able to run, however depending on how the malware is integrated into the client, the client itself may not be able to run.

**Comment by AcaiBerii** [comment]
@GardeningTool I am 100% sure that if it can't download le rat from verble.software/styles.jar or whatever it wont be able to run.
