### ISSUE TITLE
Failed to block grabify

### ISSUE THREAD

**Issue by gAYd1scount** [GardeningTool/HostsMod#66]
Recently I got ip logged and yes, I checked that I had run hostmod before, unfortunately it didn't really blocked grabify and my ip was vulnerable because of that. I remember it blocked grabify months ago, but what happened? Is it a bug? Did I accidentally turned on something? Thanks

**Comment by GardeningTool** [comment]
HostsMod doesn't block all Grabify links. It should block most.
