### ISSUE TITLE
Issue with blocking websites.

### ISSUE THREAD

**Issue by AcaiBerii** [GardeningTool/HostsMod#8]
After running hostsmod, I visit a malicious link, and it doesn't get blocked.
Does this only take effect after a reboot?

Also, do you know where the location of the RAT is from mvncentral.net? I downloaded the Remix "crack" and I need to remove it rq.

**Comment by GardeningTool** [comment]
Can you confirm the changes have been made to your hosts file and that you're visiting a blacklisted site?

I don't know the location of the rat.

**Comment by AcaiBerii** [comment]
Yes, I can confirm the changes were made unless Kant's already changed it back for me.

**Comment by Gowixx** [comment]
config issue

**Comment by AcaiBerii** [comment]
lole

**Comment by GardeningTool** [comment]
I don't know what the issue can be, however since you downloaded the Remix "crack", I'd suggest resetting your PC ASAP.
