### ISSUE TITLE
BLOCK DOMAIN BABE NLG NEWB

### ISSUE THREAD

**Issue by peedeeee** [GardeningTool/HostsMod#80]
![20210308_011110_IMG_0129](https://user-images.githubusercontent.com/90869540/158053398-6fafd118-3cba-46f1-b7eb-2dc70b30bd05.JPG)

**Comment by GardeningTool** [comment]
Could you open a PR with the necessary change so I can have a clean record of who makes what changes?

**Comment by GardeningTool** [comment]
^ Added
