### ISSUE TITLE
Black list bigrat.monster

### ISSUE THREAD

**Issue by Body-Alhoha** [GardeningTool/HostsMod#81]
Got ratted by a new version of Kant rat… it injects code into .exe and it’s not even dynamic ! It inject static code. Here’s netstat
![AED5A0A1-1011-4111-AA5C-D5694CF32E97](https://user-images.githubusercontent.com/50592096/158192705-2112f918-7ba4-44ca-8524-56f2d9913966.jpeg)

**Comment by GardeningTool** [comment]
Added

**Comment by FartCheese** [comment]
> Got ratted by a new version of Kant rat… it injects code into .exe and it’s not even dynamic ! It inject static code. Here’s netstat ![AED5A0A1-1011-4111-AA5C-D5694CF32E97](https://user-images.githubusercontent.com/50592096/158192705-2112f918-7ba4-44ca-8524-56f2d9913966.jpeg)

Wait, so what happened?

**Comment by Strezzed** [comment]
![obraz](https://user-images.githubusercontent.com/102617311/161607693-044f88f5-bdbc-44f1-94de-4dc9389e1148.png)
