### ISSUE TITLE
How to remove kant + Make less "fear" when checking if infected

### ISSUE THREAD

**Issue by Body-Alhoha** [GardeningTool/HostsMod#82]
Hi, i'm body, recently i got infected by kant/eviate rat a new version that is somehow good?

So, how to remove it ?

You will need a usb key and if you want to save your data, you will need an external usb drive

-> Reset your router
-> Get another pc that isn't infected
-> Use windows media creation tool to create a bootable usb
-> Reset your pc with that usb key

If you have saved your data
-> Delete all exe files, they may have been infected, we don't know.

Once you are back on windows, run HostsMod for never getting ratted again.
I hope for you that everything went well

If you want to know if you are infected ?
Run netstat, if you see mvncentral.net a bunch of times you are infected. Myself being infected and mvncentral.net blocked, i thought i was protected but nah. This doesn't actually stops if you are already infected but prevents to be infected.

To see if you are infected you can also download process hacker and go in network tab, search for anything where **_remote address_** is mvncentral.net.

If you see like svchost in local address the well know domain mvncentral.net It's because, in your hosts file the domain mvncentral.net is the first one, it redirect that domain to localhost. This means that process hacker will replace 127.0.0.1 to mvncentral.net in the network tab.

So my suggestion, add as blocked domain BEFORE mvncentral.net : 127.0.0.1, localhost get redirected to localhost which is the same so nothing will happen except that it process hacker it will show that.

Cheers, body, hope u got some reading xd

**Comment by 0xa00** [comment]
bro it's just an autorun exe wtf no need to get a new pc
or a new router 💀

**Comment by Body-Alhoha** [comment]
well resetting didnt worked for me idk if it was kant but it was connecting to kant domain, or maybe i'm just dumb or smth
