### ISSUE TITLE
im legit starving

### ISSUE THREAD

**Issue by 0xa00** [GardeningTool/HostsMod#87]
i cannot order my salads due to this
i'm on the verge of death by starvation
please help

**Comment by peedeeee** [comment]
You blocked etc.catering... How could you do this? I wanted to prevent being ratted by Lucas Breeden and instead I can't order my son curied lentil salads...

**Comment by 0xa00** [comment]
![a9yCDdg8](https://user-images.githubusercontent.com/73900311/160283520-ad9fc30c-898d-464c-9d1d-1a37a12832db.png)

**Comment by emmaroebreeden** [comment]
![dorfler](https://user-images.githubusercontent.com/102260419/160286690-220e28c4-3a45-49cf-8ab6-cc98fb8235da.jpg)

**Comment by 0xa00** [comment]
> ![dorfler](https://user-images.githubusercontent.com/102260419/160286690-220e28c4-3a45-49cf-8ab6-cc98fb8235da.jpg)
penguin roboticz
