### ISSUE TITLE
Still not working?

### ISSUE THREAD

**Issue by AcaiBerii** [GardeningTool/HostsMod#9]
Everything seems normal with the hosts file after modification, however after running netstat i still have multiple connections from mvncentral.net on my computer.

Btw, a factory reset did nothing.

Please help because i dont want to be doxxed. I already ran a scan with malwarebytes, windows defender and adwcleaner.

I'm sorry for spamming the issues, but this really is an issue.

**Comment by dortware** [comment]
>  however after running netstat i still have multiple connections from mvncentral.net on my computer.

Don't worry, these connections are still being blocked. If they weren't restart your PC.

**Comment by KtntKot** [comment]
Actually, if you was ratted before running this program i would recommend **FULL** factory reset.

**Comment by AcaiBerii** [comment]
I did a full factory reset.

**Comment by dortware** [comment]
> I did a full factory reset.

Then you will be safe.

**Comment by Numzskull** [comment]
> 
> 
> Everything seems normal with the hosts file after modification, however after running netstat i still have multiple connections from mvncentral.net on my computer.
> 
> Btw, a factory reset did nothing.
> 
> Please help because i dont want to be doxxed. I already ran a scan with malwarebytes, windows defender and adwcleaner.
> 
> I'm sorry for spamming the issues, but this really is an issue.

I (believe) it will still show the connections, a easy way to test if they've been blocked is going to one of the domains listed, in your web browser. Ex. mvncentral.net. 

You should get a could not connect or something similar error.

OR

Open command prompt and type ping mvncentral.net

It should say pinging 127.0.0.1

**Comment by GardeningTool** [comment]
See the **Clarification** section on the README.md.
